title: Ben Nelson

description: Therapist and counselor in Smyrna, TN
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
defaults:
  - scope:
      path: ""
    values:
      header:
        overlay_image: /Assets/4SWallpaper.jpg
        overlay_filter: 0.4
