title: Ben Nelson Counseling

header_pages:
  - index.md
  - About.md
  - Articles.md
  - Speaking.md
  - Resources.md

description: Therapist and counselor in Smyrna, TN
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache


  defaults:
  - scope:
      path: ""
    values:
      tagline: "Counselor • Writer • Speaker"
      header:
        overlay_image: /Assets/4SWallpaper.jpg
        overlay_filter: 0.4

  
