# search: false
# search_full_content: false
# search_provider: lunr 
breadcrumbs: true
words_per_minute: 200
related_posts: true


title: "Ben Nelson"

description: Therapist and counselor in Smyrna, TN
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
 # - jekyll-include-cache
defaults:
  - scope:
      path: ""
    values:
      header:
        overlay_image: /Assets/4SWallpaper.jpg
        overlay_filter: 0.4
  - scope:
      path: ""
      type: posts
    values:
      header:
        overlay_image: null
